#Creating a film
POST http://localhost:3000/film
Content-Type: application/json

{
    "name":"La Tarago3 Wala Estslam",
    "dateOfRelease":"2024-01-01 12:00:00",
    "summary":"Ahmed Mekky w Adham",
    "countryOfOrigin":"Egypt"
}