#Creating a film
POST http://localhost:3000/film
Content-Type: application/json

{
    "name":"B7bk wana kman",
    "dateOfRelease":"2024-01-01 12:5:00",
    "summary":"Nu3man",
    "countryOfOrigin":"Egypt"
}

###---------------------------------------
###Getting all films
GET http://localhost:3000/film

###---------------------------------------
###Getting specific film
GET http://localhost:3000/film/9


###---------------------------------------
###update film length
PATCH  http://localhost:3000/film/9/length
Content-Type: application/json

{
    "length":3.95
}
###---------------------------------------
###Delete a film
DELETE http://localhost:3000/film/9

